### ISSUE TITLE
Client of Discord Bot (Dangerous)

### ISSUE THREAD

**Issue by SurgicalCrow** [labdiscord/statcord.js#50]
Am i giving away my Client here?

```
const statcord = new Statcord.Client({
    **client**,
    key: "_",
})
```
 and **Client.token** has the token. So guys, is that like snipping our public bot's token without our permission?

**Comment by anishanne** [comment]
No? If you look through the code at no point is `client.token` taken or stored anywhere. The library simply gets the guild/user count and posts it to Statcord. **Your token is never recorded or taken anywhere. It never even leaves your hosting server.** Feel free to look through the code to check for that, the lib is open-sourced.

If you don't trust the library, then you can send your own post request every minute.

**Comment by tbnritzdoge** [comment]
Learn how to code before making disingenuous comments @SurgicalCrow
