### ISSUE TITLE
Support custom versions of the discord.js client

### ISSUE THREAD

**Issue by EndBug** [labdiscord/statcord.js#57]
Hi, I'm using [`discord.js-light@^3.3.6`](https://www.npmjs.com/package/discord.js-light) with `discord.js@^12.5.1` and today, while updating my bot, statcord started telling me that my client isn't a discord.js client.
From what I understand, it sees that I'm not using your same client class and stops. I'd like an option to override this check, since I know for a fact that that's a "normal" discord.js client.

**Comment by Solixity** [comment]
This can be done definitely. I'll forward this to our development team and see when it can be done 👍

**Comment by ilxlodev** [comment]
Any update on this issue? I also use a custom version of discord.js

**Comment by anishanne** [comment]
At this time, we recommend you run a fork of our library or post directly to our API.
Docs - [docs.statcord.com/#/api?id=post-bot-stats](https://docs.statcord.com/#/api?id=post-bot-stats)
