### ISSUE TITLE
CPU data not posting

### ISSUE THREAD

**Issue by asportnoy** [labdiscord/statcord.js#67]
The statcord dashboard is not showing my CPU load data, nor is the API. Memory and bandwidth are both working fine. I tried using the same code as the library to make sure it's gathering the data correctly (`require("systeminformation").currentLoad()`, `currentLoad` property on result) and it got the correct output.

I am running node.js v14.16.0 on Ubuntu 20.04.1 (VPS).

**Comment by Solixity** [comment]
Are you using the wrapper or posting straight to statcord via the REST API?

**Comment by asportnoy** [comment]
NPM library

**Comment by Solixity** [comment]
> NPM library

Try using the REST API and see if CPU data starts showing and if it isn't then we'll take a look at logs and see if we can debug something from there. Mind giving your bot's ID?

**Comment by asportnoy** [comment]
ID is 699844962057060393. Are you saying you just want me to post some sample data to see if it actually goes thru?

**Comment by Solixity** [comment]
Yeah, try sample data for the CPU load but keep the original data for servers, users, etc etc

**Comment by Solixity** [comment]
Another thing I can suggest is switching the library over to `statcord.js-beta` @ https://npmjs.com/statcord.js-beta

**Comment by asportnoy** [comment]
The post response shows the CPU data I provided, but when I use the get endpoint, it shows 0 still.

Post request body:
```js
{
    "id": "BOT ID",
    "key": "API KEY",
    "servers": "SERVER COUNT",
    "users": "USER COUNT",
    "cpuload": "50",
    "active": [],
    "popular": [],
    "commands": "0",
    "memactive": "0",
    "memload": "0",
    "bandwidth": "0"
}
```
Post request response:
```js
{
    "error": false,
    "msg": {
        // [...]
        "cpuload": "50",
        // [...]
    }
}
```

Get request response:
```js
{
    "error": false,
    "msg": {
        // [...]
        "cpuload": "0",
        // [...]
    }
}
```

**Comment by Solixity** [comment]
Alright, @anishanne can you look into this as well? I'm betting my money on redis being wack again :)

**Comment by asportnoy** [comment]
Has there been any further info on this?

**Comment by Solixity** [comment]
As far as I've personally heard and/or seen, no. I'll try testing stuff out tonight and see if I can pinpoint the issue without bringing down 1/2 of the site 😅

**Comment by asportnoy** [comment]
@Solixity Any updates? Still showing 0%.

**Comment by Solixity** [comment]
Sadly not @asportnoy.
I'm still thinking it's redis being stupid but as far as I know, I don't have access to redis and Anish (the other lead dev) has exams to take care of as well as anyone else with access to redis.
