### ISSUE TITLE
Bot status is not updated correctly

### ISSUE THREAD

**Issue by EndBug** [labdiscord/statcord.js#80]
I've noticed that my bot often appears as "offline" in Statcord, even though I post regularly to the API using the `autopost` function of this library.
I've also looked at the logs and posts are happening every 60 seconds and are successful.
Is it because there are no changes from one post to the other (like no new commands, users, or guilds)?
Link to my bot's Statcord page: https://statcord.com/bot/475421235950518292

**Comment by Solixity** [comment]
With Statcord (in it's current state), it doesn't seem to pick up on the fact that a successful post has occurred within x amount of minutes. [Syncing your bot here would fix this issue temporarily.](https://statcord.com/bot/475421235950518292/manage#danger)
