### ISSUE TITLE
Autoposting interval timing issues

### ISSUE THREAD

**Issue by wrac4242** [labdiscord/statcord.js#81]
## issue 
Using the auto-posting section, my bot is getting rate-limited on every other post.
![image](https://user-images.githubusercontent.com/42539664/156895483-4dd1621a-c58a-4087-8e36-f3cf58861de4.png)
This seems to be caused by the posts not being spaced a minute apart 
on further inspection of the issue, I believe this is caused by my hosting machine taking a long time to send the post request

On further inspection of the issue, it seems to be caused by [this line](https://github.com/labdiscord/statcord.js/blob/63898d6d2a69aef0a76484756d83cccf77bf4d77/src/Statcord.js#L217), which auto-posts every minute

this could potentially be solved by changing it to use `setTimeout`, as it is used with error handling [in this line](https://github.com/labdiscord/statcord.js/blob/63898d6d2a69aef0a76484756d83cccf77bf4d77/src/Statcord.js#L172)

**Comment by Solixity** [comment]
As far as I recall, in the Discord Server, you mentioned that you use Cloudflare Workers, correct?

**Comment by wrac4242** [comment]
in this case, it is hosted separately to that on a raspberry pi, cloudflare workers arent sufficient for communicating with discord to get the server count. Its currently hosted on a raspberry pi 2b

**Comment by Solixity** [comment]
Well I don't have this problem personally using the statcord library but try changing _1000_ to _2000_ in the code and see how that goes for you. If it fixes it then I'll release a new version that changes it from 1000 to 10000 or 2000, depends on how it goes.

**Comment by wrac4242** [comment]
Changing the time from 60000 to 120000 did work, creating a pr now

**Comment by wrac4242** [comment]
checking back on this, the only errors I have received since using that value has been the 5xx errors and some dns errors on my side, so this seems to fix this on slower devices
